POST http://localhost:3000/email/send
Content-Type: "application/x-www-form-urlencoded"

{
    "name": "LAHNA Sanaa",
    "email": "lahna.sanaa@gmail.com",
    "subject": "Demande de contact pour une mission",
    "content": "Salut Yassine"
}